.Dd September 24, 2015
.Dt DJVIEW4 1
.Os
.Sh NAME
.Nm djview4
.Nd standalone DjVu viewer
.Sh SYNOPSIS
.Nm djview4
.Op options
.Op Ar
.Sh DESCRIPTION
.Nm
is a standalone viewer for DjVu files.
Features include navigating documents, zooming and panning page images,
producing and displaying thumbnails, displaying document outlines,
searching documents for particular words in the hidden text layer,
copying hidden text to the clipboard,
saving pages and documents as bundled or indirect multi-page files,
and printing pages and documents.
The viewer can simultaneously display several pages
using a side-by-side or a continuous layout.
.\" COMMAND LINE ARGUMENT AND OPTIONS
.Pp
This program can run as a standalone program
or as a slave process for the DjVu browser plugin
.Xr nsdejavu 1 .
When running as a standalone program, the command line argument can be:
.Bl -bullet
.It
a filename of a valid DjVu document
.It
a URL of a local or remote DjVu document of the form
.Dl Lk http://.../file.djvu?djvuopts&keyword=value
The optional
.Dq djvuopts
can specify various options using a syntax similar to that of CGI arguments.
This is useful for a browser plugin as there are no command line arguments.
In the case of a standalone viewer,
the options can be specified as command line arguments.
Browsing remote DjVu documents with the standalone viewer
is less efficient than using the browser plugin:
the standalone viewer does not benefit from the browser
caching strategies and proxy settings.
Proxy settings for the standalone viewer can be set
independently with the preferences dialog.
.El
.Pp
An extensive list of options are recognized and described in
.Xr nsdejavu 1 .
Most options can be specified as command line arguments
to the standalone viewer, starting with the customary dash character,
or using the syntax of CGI arguments in the document URL.
Some options however are only meaningful as command line arguments;
other options are only recognized when running the X11 version of
.Nm .
.Pp
The command line options are as follows:
.Bl -tag -width Ds
.It Fl help
Display a brief help message and exit.
.It Fl verbose
Prints informational messages on the console.
This option is very useful because it displays
messages about unrecognized constructs
in the DjVu annotation and hyperlink layers.
.It Fl fs , fullscreen
Start
.Nm
in full screen mode.
Use the ESC key to exit the full screen mode.
.It Fl slideshow Ns Op = Ns Ar arg
Start
.Nm
in slide show mode.
The optional numerical argument
.Ar arg
specifies the number of seconds before turning each page.
Use the ESC key to exit the slide show mode.
.It Fl style Ns = Ns Ar stylename
Specify the graphical user interface style.
The recognized values of
.Ar stylename
depend on the installed version of the Qt toolkit.
Common style names include
.Cm cde ,
.Cm motif ,
.Cm plastique ,
.Cm platinum ,
and
.Cm windows .
.El
.\" X11 Options
.Pp
The following command line options are recognized by the X11 version of
.Nm .
Unlike most
.Nm
options, the X11 options that demand an argument
do not use the
.Sq =
character to introduce their argument.
.Bl -tag -width Ds
.It Fl display Ar displayname
Let
.Nm
windows appear on the X11 display
.Ar displayname .
.It Fl geometry Ar W Ns x Ns Ar H Ns + Ns Ar X Ns + Ns Ar Y
Specify the initial size and position of the first window
using the traditional X11 geometry specification syntax.
The integer arguments
.Ar W
and
.Ar H
represent the initial window width and height.
The numerical arguments
.Ar X
and
.Ar Y
indicate the window position relative to the top left corner of the screen.
.It Fl name Ar name
Set the application name.
.It Fl title Ar title
Set the title of the first window.
.It Fl fn Ar fontname , Fl font Ar fontname
Specify the default font used for buttons and menus.
The font should be specified using a X logical font description string.
.It Fl bg Ar color , Fl background Ar color
Specify the default background color used for interface elements.
The color should be given as a standard X11 color name.
.It Fl fg Ar color , Fl foreground Ar color
Specify the default foreground color used for interface elements.
The color should be given as a standard X11 color name.
.It Fl btn Ar color
Specify the default button color.
The color should be given as a standard X11 color name.
.It Fl ncols Ar count
Limit the number of colors allocated on a 8 bit display.
The default color cube contains 216 distinct colors.
.It Fl cmap
Force the allocation of a private color map on a 8-bit display.
This might increase the color quality but cause flashing
when the viewer window gets activated.
.El
.\" GENERAL OPTIONS
.Pp
The following options can be specified as command line options
or can be passed by augmenting the document URL as described above.
The keywords are derived from the option names by removing the initial dashes.
.Bl -tag -width Ds
.It Fl page Ar pagename
Display a specific document page.
The viewer first searches a page whose identifier matches the argument
.Ar pagename .
Otherwise, if
.Ar pagename
is a number preceded by either
.Sq +
or
.Sq - ,
the viewer performs a displacement relative to the current page.
Otherwise, starting from the current page and wrapping around
it searches for a page whose title matches
.Ar pagename .
Otherwise, if
.Ar pagename
is numerical, it is interpreted as an ordinal page number.
Otherwise, and finally, the viewer searches a page whose name matches
.Ar pagename .
.\" FIXME how is a page 'identifier' different from a page 'name'
.It Fl pageno Ar pagenumber
The page searching algorithm for
.Fl page
can cause ambiguities when page titles can be interpreted as numbers.
The
.Ar pagenumber
argument
is always interpreted as an ordinal page number.
This option is less portable than
.Fl page ,
because it is not recognized by earlier versions of the djvu plugin.
When using this option is necessary, it is advisable to use both the
.Fl page
and
.Fl pageno
options.
.It Fl zoom Ar zoomfactor
Specify the initial zoom factor.
Unless the toolbar, pop-up menu and keyboard are disabled,
the user will be able to change the zoom factor.
Legal values of
.Ar zoomfactor
are:
.Pp
.Bl -hang -compact -width one2one
.It Cm number
Magnification factor in the range from 10% to 999%.
.It Cm one2one
Select the
.Dq one-to-one
mode.
.It Cm width
Select the
.Dq fit width
mode.
.It Cm page
Select the
.Dq fit page
mode.
.It Cm stretch
Stretch the image to the plugin window size.
.El
.It Fl showposition Ns = Ns Ar px , Ns Ar py
Specify a point in the current page that should be as close as possible
to the center of the window.
The horizontal and vertical positions
.Ar px
and
.Ar py
in the current page are given as fractions in the range from 0 to 1.
For instance,
.Dq 0,0
designates the upper left corner of the page,
.Dq 0.5,0.5
is the center, and
.Dq 1,1
is the lower right corner.
.It Fl mode Ns = Ns Ar modespec
Specify the initial display mode.
Unless the toolbar and pop-up menu are disabled,
the user will be able to change it.
Legal values of
.Ar modespec
are:
.Pp
.Bl -hang -compact -width color
.It Cm color
Display the color image.
.It Cm bw
Display the foreground mask only.
.It Cm fore
Display the foreground only.
.It Cm back
Display the background only.
.It Cm text
Overlay the hidden text over the color image.
.El
.It Fl hor_align Ns = Ns Ar keyword , Fl halign Ns = Ns Ar keyword
Specify the horizontal position of the page in the viewer window.
This does not specify what part of the page will be shown, but rather
how margins will be laid out around the page in the plugin window.
Legal values of
.Ar keyword
are
.Cm left ,
.Cm center ,
and
.Cm right .
.It Fl ver_align Ns = Ns Ar keyword , Fl valign Ns = Ns Ar keyword
Specify the vertical position of the page in the viewer window.
This does not specify what part of the page will be shown, but rather
how margins will be laid out around the page in the plugin window.
Legal values of
.Ar keyword
are
.Cm top ,
.Cm center ,
and
.Cm bottom .
.It Fl cache Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable the caching of fully decoded pages of the document.
Caching is on by default for documents whose URL contains a
.Pa djvu
or
.Pa djv
extension.
.It Fl continuous Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable the continuous layout of multipage documents.
.It Xo
.Fl sidebyside Ns = Ns Cm yes Ns | Ns Cm no ,
.Fl side_by_side Ns = Ns Cm yes Ns | Ns Cm no
.Xc
Enable or disable the side-by-side layout of multipage documents.
.It Fl coverpage Ns = Ns Cm yes Ns | Ns Cm no
Specify whether the cover page must be displayed alone
when multipage documents are shown in side-by-side layout.
.It Fl righttoleft Ns = Ns Cm yes Ns | Ns Cm no
Specify whether pages should be arranged right-to-left
when multipage documents are shown in side-by-side layout.
.It Fl layout Ns = Ns Ar keyword Ns Op , Ns Ar keyword Ns Op , Ns ...
Specify the layout settings using a single list of comma-separated keywords.
The following keywords are recognized:
.Pp
.Bl -hang -compact -width coverxxxnocover
.It Cm single
Disable the side-by-side and continuous modes.
.It Cm double
Enable the side-by-side mode.
.It Cm continuous
Enable the continuous mode.
.It Cm cover , nocover
First page treatment in side-by-side mode.
.It Cm ltor , rtol
Layout direction for side-by-side mode.
.It Cm gap , nogap
Specify whether there is a gap between pages.
.El
.It Fl scrollbars Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable the presence of scroll bars
when the full image size exceeds the plugin window size.
The default is yes.
.It Fl frame Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable the display
of a thin frame and shadow around the DjVu images.
Frames are enabled by default.
.It Fl background Ns = Ns Ar color
Specify the
.Ar color
of the background border displayed around the document
in hexadecimal as either
.Ar RRGGBB
or
.Pf # Ar RRGGBB .
.It Fl toolbar Ns = Ns Ar keyword Ns Op (,|+|-) Ns Ar keyword Ns Op Ns ...
Controls the appearance and the contents of the toolbar.
The argument is composed of a number of keywords
separated by characters comma, plus or minus.
The appearance of the toolbar is controlled by keywords
placed before the first plus or minus.
The following keywords are recognized in this context:
.Pp
.Bl -hang -compact -width bottom
.It Cm no
Disable toolbar.
.It Cm always
Displays the toolbar.
.It Cm auto
Enable toolbar autohide mode (not implemented).
.It Cm top
Place toolbar along the top edge.
.It Cm bottom
Place toolbar along the bottom edge.
.El
.Pp
The content of the toolbar is controlled
by keywords placed after the first plus or minus.
Each keyword adds (after a plus) or removes (after a minus)
a particular toolbar button or group of buttons.
The initial content of the toolbar is determined by the first plus or minus.
When this is a plus, the toolbar is initially empty.
When this is a minus, the toolbar initially contains
the default selection of buttons.
The following keywords are recognized:
.Pp
.Bl -hang -compact -width pagecombo
.It Cm modecombo
the display mode selection tool.
.It Cm zoomcombo
the zoom selection tool.
.It Cm zoom
the zoom buttons.
.It Cm select
the selection button.
.It Cm rotate
the image rotation buttons.
.It Cm find
the text search button.
.It Cm new
the new window button.
.It Cm open
the open new document button.
.It Cm save
the save button.
.It Cm print
the print button.
.It Cm layout
the page layout buttons.
.It Cm pagecombo
the page selection tool.
.It Cm firstlast
the first-page and last-page buttons.
.It Cm prevnext
the previous- and next-page buttons.
.It Cm backforw
the back and forward buttons.
.It Cm help
the contextual help button.
.El
.Pp
For the sake of backward compatibility,
the keywords
.Cm fore ,
.Cm fore_button ,
.Cm back ,
.Cm back_button ,
.Cm bw ,
.Cm bw_button ,
.Cm color ,
and
.Cm color_button
are interpreted as
.Cm modecombo ;
the keyword
.Cm rescombo
is a synonym of
.Cm zoomcombo ;
the keywords
.Cm pan ,
.Cm zoomsel ,
and
.Cm textsel
are interpreted as
.Cm select ;
and the keyword
.Cm doublepage
is interpreted as
.Cm layout .
All other keywords are ignored.
.It Fl menubar Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable the presence of the menu bar
located on top of the window.
.It Fl statusbar Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable the presence of the status bar
located at the bottom of the window.
.It Fl sidebar Ns = Ns Ar keyword Ns Op , Ns Ar keyword Ns Op , Ns Ar ...
Control the dockable panels.
The argument is a comma separated list of keywords.
A first group of keywords selects which panels are affected.
Omitting these keywords selects all panels.
.Pp
.Bl -hang -compact -width outlinexxbookmarks
.It Cm thumbnails
the thumbnail panel.
.It Cm outline , bookmarks
the outline panel.
.It Cm search , find
the search panel.
.El
.Pp
A second group of keywords then controls the visibility
and the position of the selected panels.
.Pp
.Bl -hang -compact -width outlinexxbookmarks
.It Cm yes , true
Show the specified panels (default).
.It Cm no , false
Hide the specified panels.
.It Cm left
Dock specified panels on the left side.
.It Cm right
Dock specified panels on the right side.
.It Cm top
Dock specified panels on the top side.
.It Cm bottom
Dock specified panels on the bottom side.
.El
.It Fl thumbnails Ns = Ns Ar keyword Ns Op , Ns Ar keyword Ns Op , Ns ...
Compatibility alias for
.Fl sidebar Ns = Ns Cm thumbnails
.It Fl outline Ns = Ns Ar keyword Ns Op , Ns Ar keyword Ns Op , Ns ...
Compatibility alias for
.Fl sidebar Ns = Ns Cm outline
.It Fl menu Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable the pop-up menu.
.It Fl keyboard Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable the DjVu plugin keyboard shortcuts.
The default is
.Cm yes
(enabled).
Note that disabling the keyboard handling
does not disable the shortcuts associated with active menus,
visible toolbars and sidebars; see
.Fl menu ,
.Fl menubar ,
.Fl toolbar ,
and
.Fl sidebar .
.It Fl mouse Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable mouse interaction for panning and selecting.
The default is
.Cm yes
(enabled).
.It Fl links Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable hyper-links in the DjVu image.
Hyper-links are enabled by default.
.It Xo
.Sm off
.Fl highlight No =
.Ar x , y , w , h
.Op , Ar color
.Sm on
.Xc
Display a highlighted rectangle at the specified coordinates
in the current page and with the specified color.
The coordinates
.Ar x ,
.Ar y ,
.Ar w
and
.Ar h
are measured in document image coordinates (not screen coordinates).
The origin is set at the bottom left corner of the image.
Specify the
.Ar color
in hexadecimal as either
.Ar RRGGBB
or
.Pf # Ar RRGGBB .
Multiple highlighted zones can be specified
and can be interspersed with multiple
.Fl page
options.
.It Fl find Ns = Ns Ar string
Highlight occurrences of the given
.Ar string .
This option works when the document contains a hidden text layer.
It can be used in conjunction with
.Fl sidebar Ns = Ns Cm find
to display the text searching interface.
The
.Ar string
can be terminated by a slash
.Pq Sq /
followed by letters specifying search options.
The following letters are recognized:
.Pp
.Bl -hang -compact -width RR
.It Cm c
Case-sensitive search.
.It Cm C
Case-insensitive search (default).
.It Cm w
Search hits start on word boundaries (default).
.It Cm W
Ignore word boundaries.
.It Cm r
Regular expression search.
.It Cm R
String search (default).
.El
.It Fl rotate Ns = Ns Cm 0 Ns | Ns Cm 90 Ns | Ns Cm 180 Ns | Ns Cm 270
Rotate the image counter-clockwise by the specified angle.
.It Fl print Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable printing the DjVu document.
Printing is enabled by default.
.It Fl save Ns = Ns Cm yes Ns | Ns Cm no
Enable or disable saving the DjVu document.
Saving is enabled by default.
.It Fl passive
Cause the DjVu image to be displayed in a manner
similar to an ordinary web image.
The default zoom factor is changed to
.Cm page .
The toolbar, the status bar, the scrollbars,
the menus, and the keyboard shortcuts are disabled.
.It Fl passivestretch
Cause the DjVu image to be displayed in a manner
similar to an ordinary web image.
The default zoom factor is changed to
.Cm stretch .
The toolbar, the status bar, the scrollbars,
the menus, and the keyboard shortcuts are disabled.
.It Fl nomenu , notoolbar , noscrollbars
These options were recognized by some versions of the DjVu viewers
and are honored for the sake of backward compatibility.
A warning message is printed when
.Fl verbose
is active.
.It Fl logo , textsel , search
These options were recognized by some versions of the DjVu viewers
but are currently not implemented by
.Nm .
A warning message is printed when
.Fl verbose
is active.
.El
.Ss Usage
Most features can be accessed using the menus, the toolbar,
the side bar or the pop-up menu shown when the right mouse button
is pressed over a DjVu image.
Detailled help can be accessed by clicking the contextual help icon
from the toolbar and then clicking on various section
of the djview user interface.
The following table lists some useful key combinations
recognized when the djvu document is active:
.Pp
.Bl -hang -compact -width UpxxDownxxLeftxxRight
.It Cm SHIFT+F1
Activate the contextual help.
.It Cm 1 , 2 , 3
Change zoom to 100%, 200% and 300%.
.It Cm Up , Down , Left , Right
Scroll the image in the given direction.
.It Cm Home
Display top left corner of the image.
.It Cm End
Display bottom right corner of the image.
.It Cm Control+Home
Go to the beginning of the document.
.It Cm Control+End
Go to the end of the document.
.It Cm Space , Return
Scroll down or go to next page.
.It Cm Backspace
Scroll up or go to previous page.
.It Cm Page Down
Go to the next page.
.It Cm Page Up
Go to the previous page.
.It Cm + , -
Zoom in and out.
.It Cm \&,
Rotate image.
.It Cm W
Select the
.Dq fit width
zooming mode.
.It Cm P
Select the
.Dq fit page
zooming mode.
.It Cm CTRL+F , F3
Search the hidden text layer.
.It Cm CTRL+G
Go to a specific page by name or by number.
.El
.Pp
Handy effects can be achieved by holding modifier keys.
The following table lists the default assignments;
these keys are configurable from the preference dialog.
.Pp
.Bl -hang -compact -width CTRL+SHIFT
.It Cm CTRL+SHIFT
Hold these keys to show the magnification lens.
.It Cm CTRL
Hold this key to select an area with the mouse.
.It Cm SHIFT
Hold this key to display all hyperlinks.
.El
.Sh ENVIRONMENT
Setting
.Ev DJVIEW_VERBOSE
to a nonzero value is equivalent to calling
.Nm
with
.Fl verbose .
Setting
.Ev DJVIEW_OPENGL
to values 0 or 1 overrides the preference settings regarding OpenGL rendering.
.Pp
When the user clicks on a djvu hyperlink pointing to a web page,
.Nm
first tries to execute the web browser programs whose names are listed
in the colon separated environment variable
.Ev BROWSER ,
then tries sensible platform dependent defaults.
.Pp
The user interface language is determined
by first trying to find a complete set of translation files
for the language specified in the preference dialog,
then for the ISO 639 languages specified in the colon separated
environment variable
.Ev LANGUAGE ,
and finally the language specified by the system locale.
If all these searches fail, the user interface language
reverts to the english default.
.Sh SEE ALSO
.Xr ddjvu 1 ,
.Xr djvu 1 ,
.Xr nsdejavu 1 ,
.Xr tiff2pdf 1
.Sh AUTHORS
.An Leon Bottou Aq Mt leonb@users.sf.net ,
using code written for
.Xr tiff2pdf 1
by
.An Ross Finlayson .
