qdjvu.o: qdjvu.cpp moc_qdjvu.inc
qdjvuhttp.o: qdjvuhttp.cpp qdjvuhttp.h
qdjvuwidget.o: qdjvuwidget.cpp qdjvu.h qdjvuwidget.h moc_qdjvuwidget.inc
qdjviewprefs.o: qdjviewprefs.cpp qdjviewprefs.h qdjvuwidget.h qdjvu.h
qdjviewdialogs.o: qdjviewdialogs.cpp qdjviewdialogs.h \
  ui_qdjviewerrordialog.h
qdjview.o: qdjview.cpp qdjvu.h qdjvuhttp.h qdjvuwidget.h qdjview.h \
  qdjviewprefs.h qdjviewdialogs.h
djview.o: djview.cpp qdjvu.h qdjview.h qdjvuwidget.h qdjviewprefs.h
